#!/usr/bin/env bash

# echo 'Current Spline:'

# cp ../../spline.txt .

# gnuplot -persist <<EOF
# set terminal dumb 200 15
# plot 'spline.txt' with linespoints
# EOF


# echo 'Generating geometry and surface mesh...'

# /home/bm424/Applications/SALOME-9.13.0-native-UB24.04-SRC/salome -t sandTrapCreator.py > log.geomCreation

# # # COPY STL FILES FROM BASE RUN DIRECTORY BECAUSE THATS WHERE YOU'VE BEEN SAVING THEM........

# # cp -r ../../sandTrapCaseDir/surfaceMeshSTLs .

# cat surfaceMeshSTLs/*.stl > fullGeo.stl

# surfaceFeatureEdges fullGeo.stl fullGeo.fms -angle 10 > log.SFE

# echo 'Meshing Geometry...'

# cartesianMesh > log.cartesianMesh

# echo 'Improving mesh quality...'

# improveMeshQuality > log.improveMeshQuality1
# improveMeshQuality > log.improveMeshQuality2

# renumberMesh -overwrite > log.renumberMesh

cp system/controlDictSimple system/controlDict
cp system/fvSchemesSimple system/fvSchemes

echo 'Decomposing domain...'

decomposePar > log.decomposePar

echo 'Running simpleFOAM initialisation...'

mpirun -np 10 simpleFoam -parallel > log.simpleFoam 2> >(grep -v "Authorization required, but no authorization protocol specified" | grep -v '^[[:space:]]*$' >&2)


cp system/controlDictKPF1 system/controlDict
cp system/fvSchemesKPF system/fvSchemes

echo 'Running particle tracking initialisation check...'

mpirun -np 10 kinematicParcelFoam -parallel > log.KPF 2> >(grep -v "Authorization required, but no authorization protocol specified" | grep -v '^[[:space:]]*$' >&2)



#reconstructPar -fields '(U p)' -lagrangianFields '(U d)'

#foamToVTK -no-boundary


